apiVersion: apps/v1
kind: Deployment
metadata:
  name: poke-landing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poke-landing
  template:
    metadata:
      labels:
        app: poke-landing
    spec:
      containers:
        - name: poke-landing
          image: mikemazun/poke-landing:v1
          ports:
            - containerPort: 80
