apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapi-frontend
  template:
    metadata:
      labels:
        app: pokeapi-frontend
    spec:
      containers:
        - name: pokeapi-frontend
          image: docker.io/mikemazun/pokeapi-frontend:latest
          ports:
            - containerPort: 80
