apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poke-landing-ingress
spec:
  rules:
    - host: poke.midominio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: poke-landing-service
                port:
                  number: 80
